spring.application.name=aggregation-service
server.port=8080
downstream.url=http://18.118.193.87:8080

# Circuit breaker config for "aggregation" instance
resilience4j.circuitbreaker.instances.aggregation.sliding-window-size=10
resilience4j.circuitbreaker.instances.aggregation.failure-rate-threshold=50
resilience4j.circuitbreaker.instances.aggregation.wait-duration-in-open-state=10s
resilience4j.circuitbreaker.instances.aggregation.permitted-number-of-calls-in-half-open-state=3
resilience4j.circuitbreaker.instances.aggregation.automatic-transition-from-open-to-half-open-enabled=true